# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [2]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed(100)

Using TensorFlow backend.


In [3]:
(x_train , y_train) , (x_test , y_test) = cifar100.load_data()

169009152/169001437 [==============================] - 227s 1us/step


In [4]:
print(x_train.shape)

(50000, 32, 32, 3)


In [5]:
print(y_train.shape)

(50000, 1)


# 資料準備

In [6]:
x_train[0][0][0]

array([255, 255, 255], dtype=uint8)

In [7]:
print(x_test.shape)

(10000, 32, 32, 3)


In [8]:
print(y_test.shape)

(10000, 1)


# Image normalize 

# 轉換label 為OneHot Encoding

In [9]:
x_train = x_train.astype('float32')/255.0
x_test = x_test.astype('float32')/255.0

In [10]:
x_train[0][0][0]

array([1., 1., 1.], dtype=float32)

In [11]:
y_train[0]

array([19])

In [12]:
from keras.utils import np_utils

y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

In [13]:
y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [14]:
print(y_train.shape)

(50000, 100)
