## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [0]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [0]:
from sklearn.model_selection import train_test_split

X_class_1 = X[:40]
X_class_0 = X[40:]

y_class_1 = y[:40]
y_class_0 = y[40:]

# If float, should be between 0.0 and 1.0 and represent the proportion of the dataset to include in the test split.
# If int, represents the absolute number of test samples. 
X_train1 , X_test1 , y_train1 , y_test1 = train_test_split(X_class_1 , y_class_1 , test_size = 0.25)
X_train0 , X_test0 , y_train0 , y_test0 = train_test_split(X_class_0 , y_class_0 , test_size = 10)

X_train = np.concatenate((X_train1 , X_train0) , axis = 0)
X_test = np.concatenate((X_test1 , X_test0) , axis = 0)

y_train = np.concatenate((y_train1 , y_train0) , axis = 0)
y_test = np.concatenate((y_test1 , y_test0) , axis = 0)

In [6]:
print('shape of X_test:' + str(X_test.shape))
print('X_test:')
print(X_test)

print('-'*30)

print('shape of y_test:' + str(y_test.shape))
print('y_test:')
print(y_test)

shape of X_test:(20, 5)
X_test:
[[ 70  71  72  73  74]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [145 146 147 148 149]
 [  0   1   2   3   4]
 [ 65  66  67  68  69]
 [195 196 197 198 199]
 [ 95  96  97  98  99]
 [ 50  51  52  53  54]
 [ 30  31  32  33  34]
 [705 706 707 708 709]
 [535 536 537 538 539]
 [430 431 432 433 434]
 [665 666 667 668 669]
 [795 796 797 798 799]
 [220 221 222 223 224]
 [480 481 482 483 484]
 [390 391 392 393 394]
 [575 576 577 578 579]
 [295 296 297 298 299]]
------------------------------
shape of y_test:(20,)
y_test:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
